//
//  SUParameterAssert.h
//  Sparkle
//
//  Created by Mayur Pawashe on 2/28/16.
//  Copyright © 2016 Sparkle Project. All rights reserved.
//

#ifndef SUParameterAssert_h
#define SUParameterAssert_h

// Work around a warning generated by some versions of Xcode that we still support,
// when using NSParameterAssert
#define SUParameterAssert(condition) \
NSAssert((condition), @"Invalid parameter not satisfying: %@", @(#condition))

#endif /* SUParameterAssert_h */
