#!/bin/sh
# Conditionally copy XPC services into the framework

if [[ "$SPARKLE_EMBED_INSTALLER_LAUNCHER_XPC_SERVICE" -eq 1 ]]; then
    mkdir -p "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}"
    ditto "${BUILT_PRODUCTS_DIR}/${INSTALLER_LAUNCHER_NAME}.xpc" "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}/${INSTALLER_LAUNCHER_NAME}.xpc"
fi

if [[ "$SPARKLE_EMBED_DOWNLOADER_XPC_SERVICE" -eq 1 ]]; then
    mkdir -p "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}"
    ditto "${BUILT_PRODUCTS_DIR}/${DOWNLOADER_NAME}.xpc" "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}/${DOWNLOADER_NAME}.xpc"
fi

if [[ "$SPARKLE_EMBED_INSTALLER_STATUS_XPC_SERVICE" -eq 1 ]]; then
    mkdir -p "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}"
    ditto "${BUILT_PRODUCTS_DIR}/${INSTALLER_STATUS_NAME}.xpc" "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}/${INSTALLER_STATUS_NAME}.xpc"
fi

if [[ "$SPARKLE_EMBED_INSTALLER_CONNECTION_XPC_SERVICE" -eq 1 ]]; then
    mkdir -p "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}"
    ditto "${BUILT_PRODUCTS_DIR}/${INSTALLER_CONNECTION_NAME}.xpc" "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}/${INSTALLER_CONNECTION_NAME}.xpc"
fi
