//
//  SPUInstallerProgressLocalizedStrings.h
//  Sparkle
//
//  This file is auto-generated by Configurations/generate_progress_tool_localizations.py
//  Do not edit by hand. Re-run the script after changing the strings below in
//  Sparkle/*.lproj/Sparkle.strings
//

#import <Foundation/Foundation.h>

static NSDictionary<NSString *, NSDictionary<NSString *, NSString *> *> *const SPUInstallerProgressLocalizedStringsTable = @{
    @"ar": @{
        @"Cancel Update": @"إلغاء التحديث",
        @"Updating %@": @"تحديث %@",
    },
    @"ca": @{
        @"Installing update…": @"Instal·lant l'actualització…",
        @"Updating %@": @"Actualitzant %@",
    },
    @"cs": @{
        @"Cancel Update": @"Zrušit aktualizaci",
        @"Installing update…": @"Instaluje se aktualizace…",
        @"Updating %@": @"Aktualizuje se %@",
    },
    @"da": @{
        @"Cancel Update": @"Annuller opdatering",
        @"Installing update…": @"Installerer opdatering…",
        @"Updating %@": @"Opdaterer %@",
    },
    @"de": @{
        @"Cancel Update": @"Aktualisierung abbrechen",
        @"Installing update…": @"Update installieren …",
        @"Updating %@": @"Aktualisierung von %@",
    },
    @"el": @{
        @"Cancel Update": @"Ακύρωση Ενημέρωσης",
        @"Installing update…": @"Εγκατάσταση ενημέρωσης…",
        @"Updating %@": @"Ενημέρωση %@",
    },
    @"en": @{
        @"Cancel Update": @"Cancel Update",
        @"Installing update…": @"Installing update…",
        @"Updating %@": @"Updating %@",
    },
    @"es": @{
        @"Cancel Update": @"Cancelar actualización",
        @"Installing update…": @"Instalando actualización…",
        @"Updating %@": @"Actualizando %@",
    },
    @"fa": @{
        @"Cancel Update": @"لغو به‌روزرسانی",
        @"Installing update…": @"در حال نصب به‌روزرسانی",
        @"Updating %@": @"%@ در حال به‌روزرسانی",
    },
    @"fi": @{
        @"Cancel Update": @"Peruuta päivitykset",
        @"Installing update…": @"Päivitys asennetaan…",
        @"Updating %@": @"Päivitetään %@",
    },
    @"fr": @{
        @"Cancel Update": @"Annuler la mise à jour",
        @"Installing update…": @"Installation de la mise à jour…",
        @"Updating %@": @"Mise à jour de %@",
    },
    @"he": @{
        @"Cancel Update": @"בטל את העדכון",
        @"Installing update…": @"מתקין את העדכון",
        @"Updating %@": @"עדכון %@",
    },
    @"hr": @{
        @"Cancel Update": @"Prekini aktualiziranje",
        @"Installing update…": @"Instaliranje nadogradnje …",
        @"Updating %@": @"%@ se aktualizira",
    },
    @"hu": @{
        @"Cancel Update": @"Frissítés megszakítása",
        @"Updating %@": @"%@ frissítése",
    },
    @"is": @{
        @"Installing update…": @"Set inn uppfærslu…",
        @"Updating %@": @"Uppfæri %@",
    },
    @"it": @{
        @"Cancel Update": @"Annulla Aggiornamento",
        @"Installing update…": @"Installazione aggiornamento in corso…",
        @"Updating %@": @"Aggiornamento di %@",
    },
    @"ja": @{
        @"Cancel Update": @"アップデートを中止",
        @"Installing update…": @"アップデートをインストールしています…",
        @"Updating %@": @"%@をアップデート中",
    },
    @"ko": @{
        @"Cancel Update": @"업데이트 취소",
        @"Installing update…": @"설치 중…",
        @"Updating %@": @"%@ 업데이트 중",
    },
    @"nb": @{
        @"Cancel Update": @"Avbryt oppdateringen",
        @"Installing update…": @"Installerer oppdateringen…",
        @"Updating %@": @"Oppdaterer %@",
    },
    @"nl": @{
        @"Cancel Update": @"Annuleer update",
        @"Installing update…": @"Update installeren…",
        @"Updating %@": @"%@ bijwerken…",
    },
    @"nn": @{
        @"Cancel Update": @"Avbryt oppdateringa",
        @"Installing update…": @"Installerer oppdateringa…",
        @"Updating %@": @"Oppdaterer %@",
    },
    @"pl": @{
        @"Cancel Update": @"Anuluj uaktualnianie",
        @"Installing update…": @"Instalowanie uaktualnienia…",
        @"Updating %@": @"Uaktualniam %@",
    },
    @"pt-BR": @{
        @"Cancel Update": @"Cancelar Atualização",
        @"Installing update…": @"Instalando atualização…",
        @"Updating %@": @"Atualizando o app %@",
    },
    @"pt-PT": @{
        @"Cancel Update": @"Cancelar actualização",
        @"Installing update…": @"A instalar actualização…",
        @"Updating %@": @"A actualizar o %@",
    },
    @"ro": @{
        @"Cancel Update": @"Anulează actualizarea",
        @"Installing update…": @"Instalează actualizarea…",
        @"Updating %@": @"Actualizează %@",
    },
    @"ru": @{
        @"Cancel Update": @"Отменить обновление",
        @"Installing update…": @"Устанавливаю обновление…",
        @"Updating %@": @"Обновляю %@",
    },
    @"sk": @{
        @"Cancel Update": @"Zrušiť aktualizáciu",
        @"Installing update…": @"Inštaluje sa aktualizácia…",
        @"Updating %@": @"Aktualizuje sa %@",
    },
    @"sl": @{
        @"Cancel Update": @"Prekliči posodabljanje",
        @"Installing update…": @"Nameščanje posodobitve …",
        @"Updating %@": @"Posodabljam %@",
    },
    @"sv": @{
        @"Cancel Update": @"Avbryt uppdatering",
        @"Installing update…": @"Installerar uppdatering…",
        @"Updating %@": @"Uppdaterar %@",
    },
    @"th": @{
        @"Cancel Update": @"ยกเลิกอัพเดท",
        @"Installing update…": @"กำลังติดตั้งอัพเดท…",
        @"Updating %@": @"กำลังอัพเดท %@",
    },
    @"tr": @{
        @"Cancel Update": @"Güncellemeden Vazgeç",
        @"Installing update…": @"Güncelleme kuruluyor…",
        @"Updating %@": @"%@ güncelleniyor",
    },
    @"uk": @{
        @"Cancel Update": @"Відмінити оновлення",
        @"Installing update…": @"Встановлюю оновлення…",
        @"Updating %@": @"Оновлюю %@",
    },
    @"vi": @{
        @"Cancel Update": @"Hủy cập nhật",
        @"Installing update…": @"Đang cài đặt bản cập nhật…",
        @"Updating %@": @"Đang cập nhật %@",
    },
    @"zh_CN": @{
        @"Cancel Update": @"取消更新",
        @"Installing update…": @"正在安装更新…",
        @"Updating %@": @"正在更新%@",
    },
    @"zh_HK": @{
        @"Cancel Update": @"取消更新",
        @"Installing update…": @"安裝緊更新⋯",
        @"Updating %@": @"更新緊 %@",
    },
    @"zh_TW": @{
        @"Cancel Update": @"取消更新",
        @"Installing update…": @"正在安裝更新項目⋯",
        @"Updating %@": @"正在更新%@",
    },
};
