name: "Build & Publish Release"

on:
  release:
    types: [prereleased, released]

concurrency: 
  group: publish-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: "Publish binaries for release"
    runs-on: macos-11

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: "Archive release distribution"
        run: |
          xcodebuild archive -project Sparkle.xcodeproj \
            -scheme Distribution \
            -configuration Release \
            -derivedDataPath build \
            -archivePath build/XcodeArchives/Sparkle.xcarchive

      - name: "Generate XCFramework"
        run: |
          xcodebuild \
            -create-xcframework \
            -framework "build/XcodeArchives/Sparkle.xcarchive/Products/Library/Frameworks/Sparkle.framework" \
            -debug-symbols "build/XcodeArchives/Sparkle.xcarchive/dSYMs/Sparkle.framework.dSYM" \
            -output "build/Sparkle.xcframework"

      - name: "Compress XCFramework"
        run: |
          ditto -c -k --rsrc --keepParent build/Sparkle.xcframework build/Sparkle.xcframework.zip

      - name: "Capture compressed XCFramework as an artifact"
        uses: actions/upload-artifact@v2
        with:
          name: Sparkle.xcframework.zip
          path: build/Sparkle.xcframework.zip

      - name: "Publish captured artifacts to the release"
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
