name: "Build & Publish Release"

env:
  BUILDDIR: "build"

on:
  release:
    types: [prereleased, released]

concurrency: 
  group: publish-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: "Publish binaries for release"
    runs-on: macos-11

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: "Build release distribution"
        run: make release
        env:
          FORCE_MOVE_RELEASE_TAG: "YES"
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish built artifacts to the release"
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/Build/Products/Release/Sparkle-*.tar.xz;build/Build/Products/Release/Sparkle-for-Swift-Package-Manager.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
